// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiparisAPI.Data;

#nullable disable

namespace SiparisAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220612142320_b1")]
    partial class b1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SiparisAPI.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("agirlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("agirlikBirim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cikisAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("malzemeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("malzemeKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("miktar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("miktarBirim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siparisNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("siparisnot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("statu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("varisAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Siparisler");
                });
#pragma warning restore 612, 618
        }
    }
}
